### PR TITLE
Carousel Feature Added with dummy Data

### LINKED ISSUE #11: FarmArk: Add farming themed carousel to homepage
Hey Hacktoberfest participants, good to see you.

This issue's goal is to create a farming themed carousel to homepage

Add a farming-themed carousel to index.html. Make sure you use uncopyrighted images. Use 4-5 slides in the carousel, heroing different FarmArk features. Feel free to use below reference:

[Texhnext](https://technext.github.io/montana/index.html)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by Aankirz**
## Carousel Feature Added (Fresh PR)
- [x] Hacktoberfest Participant 

 ### issue number 11
- [x] New feature (non-breaking change which adds functionality)

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.

- [x] My changes generate no new warnings.

## Screenshots
Screenshot 2022-10-27 at 834 48 PM
Screenshot 2022-10-27 at 8 35 04 PM

### CODE REVIEW

**Comment by Aankirz** [comment]
@Isha307 now check :|

**Review by Isha307 — APPROVED** [review]

**Comment by Isha307** [comment]
@Aankirz Finally Accepted 🥳

**Comment by Aankirz** [comment]
> @Aankirz Finally Accepted 🥳

Finally 😃

**Comment by prathimacode-hub** [comment]
Well done. Amazing work. @✔👌Aankirz

**Pull request merged**
