### PR TITLE
Blogs Page added with uncopyrighted images and Linked in navbar and f…

### LINKED ISSUE #10: FarmArk: Make a "Blogs" Page with Blog Cards
Hey Hacktoberfest participants, good to see you.

Build a FarmArk Blog Page with multiple cards that have some text block and accompanying images. Follow the following as a part of your checklist.

- Make sure that the images you use are uncopyrighted (Some sources are [Pexels](https://www.pexels.com/), [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/images) ).
- Use FarmArk relevant text and images (feel free to use your creativity)
- Make sure that Blog is linked in all correct places (navbar, footer, etc.)

Feel free to use the below link as a reference:
[Blog Top 50](https://detailed.com/50/)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

### PR DESCRIPTION
**Pull request by Aankirz**
## Blogs Page added with uncopyrighted images and Linked in navbar and footer
- [x] Hacktoberfest Participant 

 ### issue number 10
- [x] New feature (non-breaking change which adds functionality)

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.

- [x] My changes generate no new warnings.

## Screenshots

Screenshot 2022-10-29 at 7 07 36 PM

Screenshot 2022-10-29 at 7 07 50 PM

### CODE REVIEW

**Comment by Aankirz** [comment]
@Isha307 Please review :)

**Review by Isha307 — APPROVED** [review]
Approved :D

**Comment by Isha307** [comment]
Again the same issue arose, There is two way to solve this one is what we did in the last PR and the other is this https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github
I want you to solve this and learn a new thing, if you need help ping me :)

**Comment by Aankirz** [comment]
> Again the same issue arose, There is two way to solve this one is what we did in the last PR and the other is this https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github I want you to solve this and learn a new thing, if you need help ping me :)

Ohh, wow ! Thanks for this doc, didn't knew abt this, learned a new thing.

Thanks again @Isha307 😌, Ig now everything's fine :))

**Review by Isha307 — APPROVED** [review]

**Review by prathimacode-hub — COMMENTED** [review]
PR approved. Impressive work. Well done. ✔👌@Aankirz

**Pull request merged**
