### PR TITLE
About Us Page Added

### PR DESCRIPTION
**Pull request by Aankirz**
## About Us Page Added added with uncopyrighted images 
- [x] Hacktoberfest Participant 

 ### issue number 4
- [x] New feature (non-breaking change which adds functionality)

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.

- [x] My changes generate no new warnings.

## Video (30sec)
https://youtu.be/vv3FqkA-4a8

<iframe width="560" height="315" src="https://www.youtube.com/embed/vv3FqkA-4a8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Screenshots
Screenshot 2022-10-30 at 8 43 25 PM

Screenshot 2022-10-30 at 8 44 05 PM

### CODE REVIEW

**Comment by Aankirz** [comment]
@prathimacode-hub , @Isha307 pls review .

**Comment by Aankirz** [comment]
@prathimacode-hub plss accept :)

**Review by Isha307 — APPROVED** [review]

**Comment by Aankirz** [comment]
Thanks @Isha307 :))))

**Comment by Isha307** [comment]
@Aankirz All the best for your future journey :D

**Comment by Aankirz** [comment]
> @Aankirz All the best for your future journey :D

Got to learn something new from you, all the best for ur life as well :D <3

**Comment by prathimacode-hub** [comment]
Amazing work. You're doing great. @Aankirz

**Pull request merged**
