### PR TITLE
Carousel Feature Added with dummy data

### PR DESCRIPTION
**Pull request by Aankirz**
## Carousel Feature Added
- [x] Hacktoberfest Participant 

 ### issue number 11
- [x] New feature (non-breaking change which adds functionality)

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.

- [x] My changes generate no new warnings.

## Screenshots
Screenshot 2022-10-27 at 834 48 PM
Screenshot 2022-10-27 at 8 35 04 PM

### CODE REVIEW

**Review by Isha307 — COMMENTED** [review]
@Aankirz Why did you remove the footer?

**Review by Isha307 — APPROVED** [review]

**Comment by Isha307** [comment]
> No, I didn't 🧐

Yeah, I understood. The Problem is you hadn't updated the repo before creating the PR that's why it is creating conflict. Please update the repo and create a fresh PR :)

**Comment by Aankirz** [comment]
Ok :\

**Comment by Aankirz** [comment]
@Isha307 now I have resolved the footer part, Thank u for reviewing it :)

**Review by Isha307 — APPROVED** [review]

**Comment by Isha307** [comment]
> @Isha307 now I have resolved the footer part, Thank u for reviewing it :)

Still, I'm not able to merge it due to some conflict, please create a fresh PR :P

**Comment by Aankirz** [comment]
> Yeah, I understood. The Problem is you hadn't updated the repo before creating the PR that's why it is creating conflict. Please update the repo and create a fresh PR :)

Ig because of my mistake for not upd there's a conflict, but I'm unable to create a fresh pr, there's another soln u can "resolve " conflicts as a collaborator, since the code is correct.

Screenshot 2022-10-28 at 9 33 36 PM

**Comment by Isha307** [comment]
> > Yeah, I understood. The Problem is you hadn't updated the repo before creating the PR that's why it is creating conflict. Please update the repo and create a fresh PR :)
> 
> Ig because of my mistake for not upd there's a conflict, but I'm unable to create a fresh pr, there's another soln u can "resolve " conflicts as a collaborator, since the code is correct.
> 
> Screenshot 2022-10-28 at 9 33 36 PM

I have closed this PR, now u can update and create a new one :D

**Pull request closed without merging**
